#velero install     --provider aws     --plugins velero/velero-plugin-for-aws:v1.5.0     --bucket lastshot-toshot     --backup-location-config region=us-east-1 region=us-east-1     --secret-file ./creds --use-volume-snapshots=false  --use-restic --default-volumes-to-restic
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: slow22
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: io1
#   iopsPerGB: "10"
#   fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
  labels:
    app: nginx2
spec:
  # type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx2
  type: ClusterIP

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nginx-pv2
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   # storageClassName: "slow22"
#   persistentVolumeReclaimPolicy: Retain
#   volumeMode: Filesystem
#   hostPath:
#     path: /data/nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jax-deploymnt3
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: jax-pod
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-volume2
              mountPath: /data
      volumes:
        - name: nginx-volume2
          persistentVolumeClaim:
            claimName: nginx-pvc4
