apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC/jCCAeagAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTIzMDUzMTEzMTkyMFoXDTMzMDUyODEzMTkyMFowFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANQJ
    W4SQL3aA4oRyWFxjaRRQY7UNeGbR1KFm/ALFwDkxzDxd+O01FBwYpb01XK1F/AwT
    MDm0CZGoO8H7QMID6AWio05xKlXNOzbPxwHFupbFW3jWjoDYfCfi4y2+bAj4if/L
    b3mmHYMrxsUN2R/wg9ZG946EHDaUtZx9qtE+616pgr9bACJSuMlJcHcX2/Fe2Loe
    whjJMdYrVv++erw0BZ2tNy4v4GnZ1neQ1xZ9Sr795yRm+g9fw0GiaX5kXCBv53nh
    dpSWAN1JvxZixjmb1cBo7ytkyBgGYe8o08dZse/Nf5SQVXQ0+DLF1/miUuagTCic
    xkQLN1a5ZAd6P/mj8iMCAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
    /wQFMAMBAf8wHQYDVR0OBBYEFNI0FNTdIp8ORrvu2uMF9yCuXfIuMBUGA1UdEQQO
    MAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBADcfdy4tO3qWA3yatquW
    JZEp2mq7P3NSyQnGY9mSySWbPqGKeWhDedlWADu1ZbAcXpZSmw44Y9FAE0c6xtjR
    A9vs1CEWsmVHiTYGqLHLLlGxk1F1rzi/o3xxw3J3aEhSjyuWZTIRyJ6Iop3mkFoa
    xAUPmfZXP5eQwCBFPvsC2HUc5mAqynp9rJKnI8aI48D+G2twnk1RfxczKY3qfbh9
    HAUSMGiG/ohJEmxh+boq572R0BlfXZ3MogLOVwjWB68p38FvWrOcRX0LMhigw2N8
    Wvzeg9RIOdkjIkdk8JjbtpeaiDVBMF/bdVEbegViVIsN6otw97hXXtaCAyq43A8K
    1Z4=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2023-05-31T13:19:59Z"
  name: kube-root-ca.crt
  namespace: kube-system
  resourceVersion: "415"
  uid: df2ad088-5763-4e27-9a3f-51b1c7e84527
