apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  finalizers:
    - elbv2.k8s.aws/resources
  generation: 1
  labels:
    ingress.k8s.aws/stack-name: jenkins-webhook
    ingress.k8s.aws/stack-namespace: jenkins
  name: k8s-jenkins-jenkinsh-109b44bb6f
  namespace: jenkins
  resourceVersion: "334019359"
  uid: e278c4e1-c878-4646-bad7-ba93fd8d1e86
spec:
  ipAddressType: ipv4
  networking:
    ingress:
      - from:
        - securityGroup:
            groupID: sg-0e63259d49b450095
        ports:
          - port: 8080
            protocol: TCP
  serviceRef:
    name: jenkins-http
    port: http
  targetGroupARN: arn:aws:elasticloadbalancing:us-west-2:170048098570:targetgroup/k8s-jenkins-jenkinsh-109b44bb6f/e00a49007cd1f66d
  targetType: ip
status:
  observedGeneration: 1
